from django_authenticator import PROVIDERS

ALLOW_ACCOUNT_RECOVERY_BY_EMAIL = True
ALLOW_ADD_REMOVE_LOGIN_METHODS = True
EMAIL_VALIDATION = False
PASSWORD_MIN_LENGTH = 8
USE_LDAP_FOR_PASSWORD_LOGIN = False
OPENID_DISALLOW_INAMES = True
USE_RECAPTCHA = False
SIGNIN_ALWAYS_SHOW_LOCAL_LOGIN = False

#this list is duplicated in the __init__.py
SIGNIN_LOCAL_ENABLED = True
SIGNIN_AOL_ENABLED = True
SIGNIN_BLOGGER_ENABLED = True
SIGNIN_CLAIMID_ENABLED = True
SIGNIN_FLICKR_ENABLED = False
SIGNIN_GOOGLE_ENABLED = True
SIGNIN_LIVEJOURNAL_ENABLED = False
SIGNIN_OPENID_ENABLED = True
SIGNIN_TECHNORATI_ENABLED = True
SIGNIN_WORDPRESS_ENABLED = True
SIGNIN_VIDOOP_ENABLED = True
SIGNIN_VERISIGN_ENABLED = True
SIGNIN_YAHOO_ENABLED = True

#providers requiring keys are disabled by default
SIGNIN_IDENTICA_ENABLED = False
SIGNIN_TWITTER_ENABLED = False
SIGNIN_LINKEDIN_ENABLED = False
SIGNIN_FACEBOOK_ENABLED = False
